# import SummaryOfLessonOne
# import WorkMadeOnTheSpotForLessonOne

#import SummaryOfLessonTwo
#import WorkMadeOnTheSpotForLessonTwo

#import SummaryOfLessonThree
import WorkMadeOnTheSpotForLessonThree